pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.fabricmc.net/' }
    }
}

rootProject.name = 'MineAgent'

include 'api'
include 'engine'
include 'tools'
include 'fabric'
include 'neoforge'
