package com.mineagent.api.task;

/**
 * Immutable, provider-neutral view of a running body task.
 *
 * <p>The old task ledger exposed only {@code Running}. That forced the model to
 * guess whether the body was navigating, acting, blocked, or making progress.
 * A snapshot is deliberately small enough to publish every tick and contains
 * only facts produced by the executor, not claims generated by the LLM.
 */
public record TaskSnapshot(
        String stage,
        String summary,
        long completedUnits,
        long totalUnits,
        Integer targetX,
        Integer targetY,
        Integer targetZ,
        String blockedReason,
        String evidence,
        long progressVersion
) {
    public TaskSnapshot {
        stage = normalize(stage, "running");
        summary = normalize(summary, "Task is running");
        completedUnits = Math.max(0L, completedUnits);
        totalUnits = totalUnits <= 0L ? -1L : totalUnits;
        if (totalUnits > 0L) completedUnits = Math.min(completedUnits, totalUnits);
        blockedReason = blankToNull(blockedReason);
        evidence = blankToNull(evidence);
        progressVersion = Math.max(0L, progressVersion);
    }

    public static TaskSnapshot running(String stage, String summary) {
        return new TaskSnapshot(stage, summary, 0L, -1L,
                null, null, null, null, null, 0L);
    }

    public static TaskSnapshot progress(String stage, String summary,
                                        long completed, long total,
                                        Integer x, Integer y, Integer z,
                                        String blockedReason, String evidence,
                                        long progressVersion) {
        return new TaskSnapshot(stage, summary, completed, total,
                x, y, z, blockedReason, evidence, progressVersion);
    }

    public boolean hasTarget() {
        return targetX != null || targetY != null || targetZ != null;
    }

    public boolean isBlocked() {
        return blockedReason != null;
    }

    private static String normalize(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value.trim();
    }

    private static String blankToNull(String value) {
        return value == null || value.isBlank() ? null : value.trim();
    }
}
