plugins {
    id 'java-library'
    id 'maven-publish'
}

group = rootProject.group
version = rootProject.version

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'com.google.code.gson:gson:2.11.0'
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
